// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yuxxavwiimengdijdzqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1eHhhdndpaW1lbmdkaWpkenFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMzg0NzgsImV4cCI6MjA3MTYxNDQ3OH0.Zq7wiGAl8AfrpPVBZAL3Boo8zHOnyj7T4sloqfSKY-k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});